title: IoTReady
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Making IoT Simpler
color_scheme: light
accent_color: pink
header:
  title: IoTReady
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Portfolio
      url: /portfolio/
      style: link
    - label: Blog
      url: /blog/
      style: link
    - label: Docs
      url: https://iotready.github.io/docs/
      style: link
      new_window: true
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
footer:
  content: '&copy; IoTReady. All rights reserved.'
  links:
    - label: Making IoT Simpler.
      url: 'https://github.com/iotready/'
      style: link
      new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/company/jaaga-labs'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
