title: IoTReady
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Simplifying IoT
color_scheme: light
accent_color: pink
header:
  title: IoTReady
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Portfolio
      url: /portfolio/
      style: link
    - label: Open Source
      url: /open-source/
      style: link
    - label: IP
      url: /ip/
      style: link
    - label: Blog
      url: /blog/
      style: link
    # - label: Docs
      # url: https://iotready.github.io/docs/
      # style: link
      # new_window: true
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
footer:
  content: '&copy; IoTReady. All rights reserved.'
  links:
    - label: Simplifying IoT.
      url: 'https://github.com/iotready/'
      style: link
      new_window: true
  has_social: true
  social_links:
    - label: Github
      url: 'https://github.com/iotready/'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/company/jaaga-labs'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  - deploy.sh
defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      published: true
